Microsoft Windows [Version 10.0.19045.5965]
(c) Microsoft Corporation. All rights reserved.

C:\Users\esltester2\Desktop\work\indesktop\frontend>npm run start:network

> fweb@0.1.0 start:network
> set NODE_OPTIONS=--openssl-legacy-provider && set HOST=0.0.0.0 && react-scripts start

Attempting to bind to HOST environment variable: 0.0.0.0
If this was unintentional, check that you haven't mistakenly set it in your shell.
Learn more here: https://bit.ly/CRA-advanced-config
Compiled with warnings.

./src/employee/CreateEmployee.js
  Line 10:10:  'isLoading' is assigned a value but never used   no-unused-vars
  Line 15:19:  'setSuccess' is assigned a value but never used  no-unused-vars
  Line 48:13:  'response' is assigned a value but never used    no-unused-vars

./src/user/createUser.js
  Line 11:23:  'setCompanyName' is assigned a value but never used  no-unused-vars
  Line 12:16:  'setRole' is assigned a value but never used         no-unused-vars
  Line 14:19:  'setSuccess' is assigned a value but never used      no-unused-vars
  Line 15:10:  'isLoading' is assigned a value but never used       no-unused-vars
  Line 29:13:  'response' is assigned a value but never used        no-unused-vars

./src/reviewer_dashboard/Dashboard.js
  Line 14:11:  'user' is assigned a value but never used              no-unused-vars
  Line 68:9:   'rightsCategories' is assigned a value but never used  no-unused-vars

./src/reviewer_dashboard/changepass.js
  Line 15:12:  'isLoading' is assigned a value but never used  no-unused-vars
  Line 16:12:  'error' is assigned a value but never used      no-unused-vars
  Line 28:19:  'response' is assigned a value but never used   no-unused-vars

./src/audit/AuditList.js
  Line 16:10:   'editingAuditId' is assigned a value but never used      no-unused-vars
  Line 18:10:   'isSaving' is assigned a value but never used            no-unused-vars
  Line 30:9:    'handleRightsChange' is assigned a value but never used  no-unused-vars
  Line 38:9:    'handleSave' is assigned a value but never used          no-unused-vars
  Line 91:9:    'handleCancel' is assigned a value but never used        no-unused-vars
  Line 132:11:  'rightsDetails' is assigned a value but never used       no-unused-vars

./src/components/Sidebar.js
  Line 16:20:  Expected '===' and instead saw '=='  eqeqeq
  Line 21:20:  Expected '===' and instead saw '=='  eqeqeq
  Line 26:20:  Expected '===' and instead saw '=='  eqeqeq
  Line 31:20:  Expected '===' and instead saw '=='  eqeqeq
  Line 36:20:  Expected '===' and instead saw '=='  eqeqeq
  Line 49:20:  Expected '===' and instead saw '=='  eqeqeq
  Line 54:20:  Expected '===' and instead saw '=='  eqeqeq
  Line 59:20:  Expected '===' and instead saw '=='  eqeqeq
  Line 75:20:  Expected '===' and instead saw '=='  eqeqeq

./src/App.js
  Line 20:8:   'Dashboard' is defined but never used      no-unused-vars
  Line 31:8:   'Reviewer' is defined but never used       no-unused-vars
  Line 50:28:  'user' is assigned a value but never used  no-unused-vars

./src/user/CreateAdmin.js
  Line 28:13:  'response' is assigned a value but never used  no-unused-vars

./src/applications/Application.js
  Line 2:10:    'Link' is defined but never used                   no-unused-vars
  Line 41:9:    'handleDelete' is assigned a value but never used  no-unused-vars
  Line 146:13:  'response' is assigned a value but never used      no-unused-vars

./src/auth/AuthContext.js
  Line 2:17:   'Component' is defined but never used  no-unused-vars
  Line 16:37:  Expected '!==' and instead saw '!='    eqeqeq

./src/pages/RoleBasedDashboard.js
  Line 2:8:  'Dashboard' is defined but never used  no-unused-vars

./src/auth/ProtectedRoute.js
  Line 3:17:  'Component' is defined but never used  no-unused-vars

./src/pages/Signup.js
  Line 3:17:  'Component' is defined but never used  no-unused-vars

./src/hod/HodIndex.js
  Line 44:9:  'handleEmployeeAssignmentChange' is assigned a value but never used  no-unused-vars

./src/pages/Logout.js
  Line 4:17:  'Component' is defined but never used  no-unused-vars

./src/pages/Login.js
  Line 4:17:  'Component' is defined but never used  no-unused-vars

./src/applications/CreateApp.js
  Line 5:10:   'Navigate' is defined but never used                   no-unused-vars
  Line 5:20:   'useNavigate' is defined but never used                no-unused-vars
  Line 12:17:  'setRoles' is assigned a value but never used          no-unused-vars
  Line 14:10:  'last_audit_date' is assigned a value but never used   no-unused-vars
  Line 14:27:  'setLastAuditDate' is assigned a value but never used  no-unused-vars
  Line 20:19:  'setSuccess' is assigned a value but never used        no-unused-vars
  Line 74:13:  'response' is assigned a value but never used          no-unused-vars

./src/frequency/Create_freq.js
  Line 5:8:  'Swal' is defined but never used  no-unused-vars

./src/employee/IndexEmoloyee.js
  Line 73:13:  'response' is assigned a value but never used  no-unused-vars

./src/pages/Dashboard.js
  Line 7:10:   'totalUsers' is assigned a value but never used   no-unused-vars
  Line 8:10:   'totalEmp' is assigned a value but never used     no-unused-vars
  Line 9:10:   'totalFreq' is assigned a value but never used    no-unused-vars
  Line 10:10:  'totalReview' is assigned a value but never used  no-unused-vars

./src/excel/UploadExcel.js
  Line 8:12:    'selectedFile' is assigned a value but never used  no-unused-vars
  Line 160:19:  'excelHeaders' is assigned a value but never used  no-unused-vars

./src/audit/create_audit.js
  Line 9:10:    'selectedemp' is assigned a value but never used               no-unused-vars
  Line 9:23:    'setSelectedEmp' is assigned a value but never used            no-unused-vars
  Line 11:10:   'frequencyId' is assigned a value but never used               no-unused-vars
  Line 11:23:   'setFrequencyId' is assigned a value but never used            no-unused-vars
  Line 12:10:   'selectedFrequency' is assigned a value but never used         no-unused-vars
  Line 12:29:   'setSelectedFrequency' is assigned a value but never used      no-unused-vars
  Line 14:10:   'selectedUserId' is assigned a value but never used            no-unused-vars
  Line 14:26:   'setSelectedUserId' is assigned a value but never used         no-unused-vars
  Line 16:10:   'selectedApplicationId' is assigned a value but never used     no-unused-vars
  Line 16:33:   'setSelectedApplicationId' is assigned a value but never used  no-unused-vars
  Line 18:10:   'auditDate' is assigned a value but never used                 no-unused-vars
  Line 18:21:   'setAuditDate' is assigned a value but never used              no-unused-vars
  Line 19:10:   'inactive' is assigned a value but never used                  no-unused-vars
  Line 19:20:   'setInactive' is assigned a value but never used               no-unused-vars
  Line 20:10:   'rights' is assigned a value but never used                    no-unused-vars
  Line 20:18:   'setRights' is assigned a value but never used                 no-unused-vars
  Line 21:10:   'reviewerRemarks' is assigned a value but never used           no-unused-vars
  Line 21:27:   'setReviewerRemarks' is assigned a value but never used        no-unused-vars
  Line 23:19:   'setSuccess' is assigned a value but never used                no-unused-vars
  Line 25:10:   'frequencies' is assigned a value but never used               no-unused-vars
  Line 114:13:  'response' is assigned a value but never used                  no-unused-vars

Search for the keywords to learn more about each warning.
To ignore, add // eslint-disable-next-line to the line before.

